version: 0.2
phases:
  pre_build:
    commands:
      # - docker pull node:18.12.1-alpine
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - docker build -t $STACK-$ENV-backend .
      - docker tag $STACK-$ENV-backend:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$STACK-$ENV-backend:latest
      
  post_build:
    commands:
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$STACK-$ENV-backend:latest

artifacts:
 files:
  #  - "**/*"
   - imagedefinitions.json
